# Introduction {#introduction}

R is a programming language for statistical computation and graphics [@FAQR]. R has more than 14.000 packages, which are available through the Comprehensive R Archive Network (CRAN) [@CRANContributedPackages]. There are over 2050 geospatial (spatial and spatial-temporal) packages to read, write, or analyze spatial data[@bivandCRANTaskView2019]. On CRAN, packages are published and tested to maintain their functionalities and ensure compatibility. 

Currently, those packages are tested for different compilers and on different operating system, but only for the main implementation of R by R Development Core Team and ony for Debian, [@FAQR]. In CRAN, there are also result for R packages installation and checking for Debian GNU/Linux , Fedora, OS X, Solaris, and Windows [@rdevelopmentcoreteamCRANPackageCheck2019].

There are other alternative implemention exist like pqR [@nealPqRPrettyQuick2019], Microsoft R Open (MRO) [@microsoftMicrosoftOpenEnhanced2019], Renjin [@bebetadrivenRenjinJVMbasedInterpreter2019], fastR [@oracleReferenceManual2019], and TIBCO Enterprise Runtime for R (TERR) [@tibcoTIBCOEnterpriseRuntime2019]. These alternatives implementations are created to make a faster R [@hadleywickhamPerformanceAdvanced2019]. Beside the claimed faster speed, there are also some feature of these implementation that can be useful for the user like better memory management (pqR), seamless integraation to Java (Renjin), multithreade performance (MRO), and enterprise-grade analytic engine (TERR).

Unfortunately, it is not clear how will geospatial R packages behave on these implementations since these packages often relies on system libraries which installed at the system level. This means it’s not sure that they can work on different platforms and R implementations. The behavior refers to whether an R package can be installed, run, and what is the performance in the alternative R implementations.
