# Background {#background}

In this chapter, 

## Literature Review {#literature-review}

### R Implementations

In this part, various known alternative R implementation are introduced in brief.

#### GNU-R
The main implementation of R programing language is developed by the R Core Team and belongs to the GNU project. The two latest release minor release are 3.5.x and 3.6.x [@FAQR]. To avoid confussion, in this thesis the main implementation is called by GNU-R.

#### Microsoft R Open

Microsoft Open R (MRO) is created by Microsoft Corporation which has additional capabilities for better performance, reproducibility, and platform support. The latest release (MRO 3.5.3) is based on GNU-R 3.5.3. It has the compatibility with all all packages that compatible with GNU-R 3.5.3[@microsoftMicrosoftOpenEnhanced2019]. There are some docker image available for example by [@nustNuestMrodocker2019] based on Ubuntu 18.04 and [@lisicJlisicRdockercentos2017] based on CentOS 7. 

#### Renjin

Renjin is a JVM-based intepreter for the GNU-R. It is developed by BeDataDriven. Its main features are seamless integration between Java and R, big data processing, better performance on some operations, easiness to deploy in cloud infrastructure [@bebetadrivenRenjinJVMbasedInterpreter2019]. There are list of R packages in [@bedatadrivenRenjinOrgPackages2019] that show its compatibility and why it does not compatible. It shows that many geospatial R package are not compatible with Renjin.
There is a docker image available for Renjin [@nustNuestRenjindockerDockerfiles2019].

#### FastR

FastR is R implementation by Oracle that aims a high-performance [@oracleReferenceManual2019]. It is built on GraalVM, a universal virtual machine to run applications created by many programming language [@oracleGraalVM2019]. There is a docker image available for FastR [@nustNuestFastrdocker2019].

#### pqR

pqR is another R implementation created by Radford Neal that compatibles with GNU-R 2.15.1. It claims to improve GNU-R in term of speeding up many functions and perform some numerical computation in paralel on multi-core processor [@m.nealPqRPrettyQuick2019]. There is a docker image available for pqR [@nustNuestPqrdocker2019].

#### TIBCO Enterprise Runtime for R (TERR)

TERR is enterprise-grade analytic engine creted by TIBCO that has full compatibility with GNU-R. It can most common R packages without modification [@tibcoTIBCOEnterpriseRuntime2019]. There is not know docker image for this R implementation.

### Major Linux Distribution

From 10 major Linux distribution based on [@distrowatchDistroWatchComPut2019], Debian, Fedora, and Arch Linux are choosen for this research. Debian and Fedora are chosen because they are being used on CRAN and have different package managers. Arch Linux is chosen because it is a linux distribution in different spectrum compared to Debian and Fedora [@distrowatchDistroWatchComPut2019]. Ubuntu is not chosen because it is built on Debian and is widely used in the GIS & R community (cf. UbuntuGIS).  Fedora represents the Fedora/RedHat/CentOS distributions [@danielmiesslerDifferenceFedoraRedhat2019].

#### Debian

#### Fedora

#### Arch Linux

### Container Technology

### Benchmarking in R

## Aim and Objective {#aim-objective}

The main goal of this research is to understand what the performance of geospatial R packages in non-base R implementations and on platforms currently not supported by CRAN is. The behavior that we want to understand is installation and testing aspects of the R packages (i.e. whether an R package can be installed or not and whether the packages’ tests pass or not in the uncommon R implementations).
One step to achieve this goal is building testing infrastructure for those R packages based on containers to see if the R packages can run as it runs in the common R implementation. This research will design and implement a testing solution for three implementations of R (FastR, MRO, and Renjin) on all packages from CRAN’s  spatial and spatial-temporal task views (Bivand, 2019; Pebesma, 2019)`. Based on the result of testing of those R packages, this research does a benchmark of those R packages to compare the performance in different R implementation. The metric that will be used is the processing time of at least three typical geospatial workflows based on vector data, raster data, and time series data.
