# Introduction {#introduction}

## Motivation

R is a programming language for statistical computation and graphics [@FAQR]. R has more than 14.000 packages, which are available through the Comprehensive R Archive Network (CRAN) [@CRANContributedPackages]. There are over 2050 geospatial (spatial and spatial-temporal) packages to read, write, or analyze spatial data[@bivandCRANTaskView2019]. On CRAN, packages are published and tested to maintain their functionalities and ensure compatibility. 

Currently, those packages are tested for different compilers and on different operating systems, but only for the main implementation of R by R Development Core Team and only for Debian, [@FAQR]. In CRAN, there are also result for R packages installation and checking for Debian GNU/Linux, Fedora, OS X, Solaris, and Windows [@rdevelopmentcoreteamCRANPackageCheck2019].

There are other alternative implementation exist like pqR [@nealPqRPrettyQuick2019], Microsoft R Open (MRO) [@microsoftMicrosoftOpenEnhanced2019], Renjin [@bebetadrivenRenjinJVMbasedInterpreter2019], fastR [@oracleReferenceManual2019], and TIBCO Enterprise Runtime for R (TERR) [@tibcoTIBCOEnterpriseRuntime2019]. These alternatives implementations are created to make a faster R [@hadleywickhamPerformanceAdvanced2019]. Besides the claimed faster speed, there are also some features of these implementations that can be useful for the user like better memory management (pqR), seamless integration to Java (Renjin), multithreading performance (MRO), and enterprise-grade analytics engine (TERR).

Unfortunately, it is not clear how will geospatial R packages behave on these implementations since these packages often rely on system libraries installed at the system level. For example, sf package depends on GDAL, GEOS, and PROJ [@pebesmaSfSimpleFeatures2019]. This means it’s not sure whether they can work on different platforms and R implementations or not. The behavior refers to whether an R package can be installed, run, and its performance on these alternative R implementations. Besides the alternative R implementations, the platform where the R runs is also taken into consideration since the libraries are installed at the system level.

A container is computer software that is used to package and run an application and all of its dependencies [@dockerWhatContainer2019]. Since it is isolated from the external system, users can set up anything that is needed and run even complex software environments on another computer easily. This ability enables the developer to create different computational environments to run specific software. In testing, it is very useful since you can have a well-defined configuration, especially if you need specific versions dependencies [@manuelweissHowDockerMakes2016].

## Aim and Objective {#aim-objective}

The main goal of this research is to understand what the performance of geospatial R packages in non-base R implementations and on platforms currently not supported by CRAN is. The behavior that we want to understand is the installation and testing aspects of the R packages. For example, whether an R package can be installed or not and whether the packages’ tests pass or not in the uncommon R implementations.

One step to achieve this goal is creating a Docker image for all possible combinations of R implementations and platforms. The next step is testing the compatibilities of packages from spatial and spatial-temporal views on the containers from the docker image created previously. Lastly, based on the result of the previous testing, the performance of a successful combination is benchmarked in terms of speed for a typical geospatial workflow.

## Research Question

1. What are the system dependencies for the R packages for each different platform? Is the information provided by the sysreqs database complete for geospatial packages?
2. Which combinations of the platform (operating system distribution), R implementation, system libraries, and geospatial R packages that can be successfully installed?
3. What are the causes of unsuccessful installations?
4. For the compilable combination, how is the comparison between them in terms of performance?
