`r if(knitr:::is_latex_output()) '\\appendix'`

`r if(!knitr:::is_latex_output()) '# (APPENDIX) Appendix {-}'` 

<!--
If you feel it necessary to include an appendix, it goes here.
-->

# SDSR Benchmark per Chapter {#apendix-benchmark-per-chapter}

This appendix contains all the results of the benchmark per chapter in the SDSR book.

```{r Chapter01SummaryTable, results='asis', echo=FALSE}
benchmark_result_per_chapter[["01-hello.R"]] %>% 
      group_by(expr) %>% 
      summarise(mintime = min(time) / nano_time_factor,
                meantime = mean(time) / nano_time_factor,
                mediantime = median(time) / nano_time_factor,
                maxtime = max(time) / nano_time_factor) %>%
  kable(
    "latex",
    col.names = c("Docker Image", "Min", "Mean", "Median", "Max"),
    caption = "Chapter 01 Benchmark",
    booktabs = T) %>%
  kable_styling(
    latex_options = "striped"
    )
```

```{r Chapter02SummaryTable, results='asis', echo=FALSE}
benchmark_result_per_chapter[["02-Spaces.R"]] %>% 
      group_by(expr) %>% 
      summarise(mintime = min(time) / nano_time_factor,
                meantime = mean(time) / nano_time_factor,
                mediantime = median(time) / nano_time_factor,
                maxtime = max(time) / nano_time_factor) %>%
  kable(
    "latex",
    col.names = c("Docker Image", "Min", "Mean", "Median", "Max"),
    caption = "Chapter 02 Benchmark",
    booktabs = T) %>%
  kable_styling(
    latex_options = "striped"
    )
```

```{r Chapter03SummaryTable, results='asis', echo=FALSE}
benchmark_result_per_chapter[["03-Geometries.R"]] %>% 
      group_by(expr) %>% 
      summarise(mintime = min(time) / nano_time_factor,
                meantime = mean(time) / nano_time_factor,
                mediantime = median(time) / nano_time_factor,
                maxtime = max(time) / nano_time_factor) %>%
  kable(
    "latex",
    col.names = c("Docker Image", "Min", "Mean", "Median", "Max"),
    caption = "Chapter 03 Benchmark",
    booktabs = T) %>%
  kable_styling(
    latex_options = "striped"
    )
```

```{r Chapter04SummaryTable, results='asis', echo=FALSE}
benchmark_result_per_chapter[["04-Raster-Cube.R"]] %>% 
      group_by(expr) %>% 
      summarise(mintime = min(time) / nano_time_factor,
                meantime = mean(time) / nano_time_factor,
                mediantime = median(time) / nano_time_factor,
                maxtime = max(time) / nano_time_factor) %>%
  kable(
    "latex",
    col.names = c("Docker Image", "Min", "Mean", "Median", "Max"),
    caption = "Chapter 04 Benchmark",
    booktabs = T) %>%
  kable_styling(
    latex_options = "striped"
    )
```

```{r Chapter05SummaryTable, results='asis', echo=FALSE}
benchmark_result_per_chapter[["05-GeomManipulations.R"]] %>% 
      group_by(expr) %>% 
      summarise(mintime = min(time) / nano_time_factor,
                meantime = mean(time) / nano_time_factor,
                mediantime = median(time) / nano_time_factor,
                maxtime = max(time) / nano_time_factor) %>%
  kable(
    "latex",
    col.names = c("Docker Image", "Min", "Mean", "Median", "Max"),
    caption = "Chapter 05 Benchmark",
    booktabs = T) %>%
  kable_styling(
    latex_options = "striped"
    )
```

```{r Chapter06SummaryTable, results='asis', echo=FALSE}
benchmark_result_per_chapter[["06-Attributes.R"]] %>% 
      group_by(expr) %>% 
      summarise(mintime = min(time) / nano_time_factor,
                meantime = mean(time) / nano_time_factor,
                mediantime = median(time) / nano_time_factor,
                maxtime = max(time) / nano_time_factor) %>%
  kable(
    "latex",
    col.names = c("Docker Image", "Min", "Mean", "Median", "Max"),
    caption = "Chapter 06 Benchmark",
    booktabs = T) %>%
  kable_styling(
    latex_options = "striped"
    )
```

```{r Chapter07SummaryTable, results='asis', echo=FALSE}
benchmark_result_per_chapter[["07-ReferenceSystems.R"]] %>% 
      group_by(expr) %>% 
      summarise(mintime = min(time) / nano_time_factor,
                meantime = mean(time) / nano_time_factor,
                mediantime = median(time) / nano_time_factor,
                maxtime = max(time) / nano_time_factor) %>%
  kable(
    "latex",
    col.names = c("Docker Image", "Min", "Mean", "Median", "Max"),
    caption = "Chapter 07 Benchmark",
    booktabs = T) %>%
  kable_styling(
    latex_options = "striped"
    )
```

```{r Chapter08SummaryTable, results='asis', echo=FALSE}
benchmark_result_per_chapter[["08-Plotting.R"]] %>% 
      group_by(expr) %>% 
      summarise(mintime = min(time) / nano_time_factor,
                meantime = mean(time) / nano_time_factor,
                mediantime = median(time) / nano_time_factor,
                maxtime = max(time) / nano_time_factor) %>%
  kable(
    "latex",
    col.names = c("Docker Image", "Min", "Mean", "Median", "Max"),
    caption = "Chapter 08 Benchmark",
    booktabs = T) %>%
  kable_styling(
    latex_options = "striped"
    )
```

```{r Chapter09SummaryTable, results='asis', echo=FALSE}
benchmark_result_per_chapter[["09-BasePlot.R"]] %>% 
      group_by(expr) %>% 
      summarise(mintime = min(time) / nano_time_factor,
                meantime = mean(time) / nano_time_factor,
                mediantime = median(time) / nano_time_factor,
                maxtime = max(time) / nano_time_factor) %>%
  kable(
    "latex",
    col.names = c("Docker Image", "Min", "Mean", "Median", "Max"),
    caption = "Chapter 09 Benchmark",
    booktabs = T) %>%
  kable_styling(
    latex_options = "striped"
    )
```

```{r Chapter10SummaryTable, results='asis', echo=FALSE}
benchmark_result_per_chapter[["10-Ggplot2.R"]] %>% 
      group_by(expr) %>% 
      summarise(mintime = min(time) / nano_time_factor,
                meantime = mean(time) / nano_time_factor,
                mediantime = median(time) / nano_time_factor,
                maxtime = max(time) / nano_time_factor) %>%
  kable(
    "latex",
    col.names = c("Docker Image", "Min", "Mean", "Median", "Max"),
    caption = "Chapter 10 Benchmark",
    booktabs = T) %>%
  kable_styling(
    latex_options = "striped"
    )
```

```{r Chapter98SummaryTable, results='asis', echo=FALSE}
benchmark_result_per_chapter[["98-rbascis.R"]] %>% 
      group_by(expr) %>% 
      summarise(mintime = min(time) / nano_time_factor,
                meantime = mean(time) / nano_time_factor,
                mediantime = median(time) / nano_time_factor,
                maxtime = max(time) / nano_time_factor) %>%
  kable(
    "latex",
    col.names = c("Docker Image", "Min", "Mean", "Median", "Max"),
    caption = "Chapter 98 Benchmark",
    booktabs = T) %>%
  kable_styling(
    latex_options = "striped"
    )
```